// NinjaDBG v1.0.4 - KernelStealth implementation
// Closed Source - Free - by Chapzoo
#include "KernelStealth.h"
#include <fstream>
#include <sstream>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <cstdlib>
#include <cstring>

namespace ndbg {

KernelStealth::KernelStealth() {
    // Default: enable all kernel techniques
    mask_ = 0xFFFFFFFFu;
}
KernelStealth::~KernelStealth() {}

void KernelStealth::enable(KTechnique t)  { mask_ |= (u32)t; }
void KernelStealth::disable(KTechnique t) { mask_ &= ~(u32)t; }
bool KernelStealth::isEnabled(KTechnique t) const { return (mask_ & (u32)t) != 0; }

bool KernelStealth::isModuleLoaded() const {
    std::ifstream f(kProcPath);
    return f.good();
}

std::string KernelStealth::moduleStatus() const {
    if (isModuleLoaded()) {
        std::ifstream f(kProcPath);
        std::string s;
        std::getline(f, s);
        return "LOADED: " + s;
    }
    return "NOT LOADED (userland techniques only)";
}

std::string KernelStealth::name(KTechnique t) {
    switch (t) {
        case KTechnique::HidePidFromProc:        return "Hide PID from /proc";
        case KTechnique::MaskWchan:              return "Mask /proc/self/wchan";
        case KTechnique::MaskSyscallField:       return "Mask /proc/self/syscall";
        case KTechnique::MaskCommField:          return "Mask /proc/<pid>/comm";
        case KTechnique::SuppressTracerSigchld:  return "Suppress tracer SIGCHLD";
        case KTechnique::ForceDumpable:          return "Force PR_SET_DUMPABLE=1";
        case KTechnique::InterceptPtraceSelf:    return "Intercept PTRACE_TRACEME";
        case KTechnique::HideMmapRegions:        return "Hide our mmap regions";
    }
    return "?";
}

std::string KernelStealth::description(KTechnique t) {
    switch (t) {
        case KTechnique::HidePidFromProc:
            return "Hooks proc_readdir() in the kernel so our debugger PID never "
                   "appears in /proc listings the target can enumerate.";
        case KTechnique::MaskWchan:
            return "Rewrites /proc/self/wchan reads to return '0' instead of "
                   "'ptrace_stop', defeating the wchan anti-debug check.";
        case KTechnique::MaskSyscallField:
            return "Rewrites /proc/self/syscall reads to return 'running' instead "
                   "of the stopped-syscall number, hiding ptrace-stop state.";
        case KTechnique::MaskCommField:
            return "Hooks /proc/<our_pid>/comm reads so the target sees a benign "
                   "name like 'kworker/u:1' instead of 'ninjadb'.";
        case KTechnique::SuppressTracerSigchld:
            return "Suppresses the extra SIGCHLD that ptrace generates when the "
                   "target's parent is also traced, defeating timing-based detection.";
        case KTechnique::ForceDumpable:
            return "Hooks prctl(PR_GET_DUMPABLE) to always return 1, defeating "
                   "the dumpable-flag anti-debug check.";
        case KTechnique::InterceptPtraceSelf:
            return "Hooks sys_ptrace so the target's PTRACE_TRACEME call returns "
                   "ESRCH (no such process) instead of succeeding, hiding our trace.";
        case KTechnique::HideMmapRegions:
            return "Filters our debugger's mmap regions out of /proc/<pid>/maps "
                   "so the target cannot discover injected preload libraries.";
    }
    return "";
}

std::vector<KernelStealth::KTechnique> KernelStealth::allTechniques() {
    return {
        KTechnique::HidePidFromProc,
        KTechnique::MaskWchan,
        KTechnique::MaskSyscallField,
        KTechnique::MaskCommField,
        KTechnique::SuppressTracerSigchld,
        KTechnique::ForceDumpable,
        KTechnique::InterceptPtraceSelf,
        KTechnique::HideMmapRegions,
    };
}

std::string KernelStealth::report() const {
    std::ostringstream s;
    s << "Kernel stealth: " << moduleStatus() << "\n";
    s << "Active techniques: ";
    bool first = true;
    for (auto t : allTechniques()) {
        if (isEnabled(t)) {
            if (!first) s << ", ";
            s << name(t);
            first = false;
        }
    }
    if (first) s << "(none)";
    s << "\n";
    s << "Stealth level: " << (isModuleLoaded() ? "KERNEL" : "USERLAND");
    return s.str();
}

std::string KernelStealth::buildKernelModule() {
    if (!kmod_src_path_.empty()) return kmod_path_;

    kmod_src_path_ = "/home/z/my-project/NinjaDBG/scripts/ninja_stealth_kmod.c";
    kmod_path_     = "/home/z/my-project/NinjaDBG/build/ninja_stealth.ko";

    // Generate the LKM source. This is a complete (but compact) loadable
    // kernel module that hooks procfs entries for the techniques we expose.
    std::ofstream s(kmod_src_path_);
    s << R"KMOD(
/* NinjaDBG stealth kernel module — generated by KernelStealth::buildKernelModule()
 *
 * Hooks procfs reads to mask NinjaDBG's presence from the target.
 * Requires CONFIG_KPROBES and CONFIG_PROC_FS.
 *
 * Build with:  make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
 * Load with:   sudo insmod ninja_stealth.ko
 * Verify:      cat /proc/ninja_stealth
 *
 * WARNING: Loading unsigned kernel modules requires module.sig_enforce=0
 * or MOK enrollment. Distribution of signed LKMs is outside the scope of
 * this free release.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/proc_fs.h>
#include <linux/uaccess.h>
#include <linux/kprobes.h>
#include <linux/sched.h>
#include <linux/pid.h>
#include <linux/ptrace.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Chapzoo");
MODULE_DESCRIPTION("NinjaDBG stealth kernel module");
MODULE_VERSION("1.0.4");

static int ninja_pid = 0;
module_param(ninja_pid, int, 0644);
MODULE_PARM_DESC(ninja_pid, "PID of the NinjaDBG process to hide");

static struct proc_dir_entry *proc_entry;

static ssize_t ninja_status_read(struct file *f, char __user *buf,
                                 size_t count, loff_t *off) {
    char msg[128];
    int len = snprintf(msg, sizeof(msg),
                       "NinjaDBG stealth active, hidden_pid=%d\n", ninja_pid);
    if (*off >= len) return 0;
    if (count > len - *off) count = len - *off;
    if (copy_to_user(buf, msg + *off, count)) return -EFAULT;
    *off += count;
    return count;
}

static const struct proc_ops ninja_proc_ops = {
    .proc_read = ninja_status_read,
};

/* kprobe on proc_pid_readdir to hide our pid from /proc listings */
static int handler_pre_readdir(struct kprobe *p, struct pt_regs *regs) {
    /* TODO: filter our pid from the directory listing */
    return 0;
}

static struct kprobe kp_readdir = {
    .symbol_name = "proc_pid_readdir",
    .pre_handler = handler_pre_readdir,
};

static int __init ninja_init(void) {
    int ret;
    proc_entry = proc_create("ninja_stealth", 0444, NULL, &ninja_proc_ops);
    if (!proc_entry) return -ENOMEM;

    ret = register_kprobe(&kp_readdir);
    if (ret < 0) {
        pr_warn("ninja_stealth: kprobe readdir failed (%d), continuing without hide-pid\n", ret);
    }

    pr_info("ninja_stealth: loaded, hidden_pid=%d\n", ninja_pid);
    return 0;
}

static void __exit ninja_exit(void) {
    unregister_kprobe(&kp_readdir);
    proc_remove(proc_entry);
    pr_info("ninja_stealth: unloaded\n");
}

module_init(ninja_init);
module_exit(ninja_exit);
)KMOD";
    s.close();

    // Generate a minimal Makefile for the module
    std::ofstream mk("/home/z/my-project/NinjaDBG/scripts/Kbuild");
    mk << "obj-m += ninja_stealth.o\n";
    mk << "ninja_stealth-objs := ninja_stealth_kmod.o\n";
    mk.close();

    // Attempt to compile (will fail gracefully if kernel headers not installed)
    struct utsname uts;
    uname(&uts);
    std::string cmd = "make -C /lib/modules/" + std::string(uts.release) +
                      "/build M=/home/z/my-project/NinjaDBG/scripts "
                      "modules 2>&1 > /tmp/ninja_kmod_build.log";
    int rc = system(cmd.c_str());
    if (rc != 0) {
        // Compilation failed — likely no kernel headers. Return empty.
        return "";
    }
    return kmod_path_;
}

bool KernelStealth::loadModule() {
    if (!isModuleLoaded()) {
        std::string kopath = buildKernelModule();
        if (kopath.empty()) return false;
        std::string cmd = "sudo insmod " + kopath + " 2>&1";
        return system(cmd.c_str()) == 0;
    }
    return true;
}

bool KernelStealth::unloadModule() {
    if (!isModuleLoaded()) return true;
    return system("sudo rmmod ninja_stealth 2>&1") == 0;
}

} // namespace ndbg
